MESSAGE("ERGC> Try to find CImg.h library...")

FIND_PATH( CIMG_INCLUDE_DIR
	NAMES "CImg.h"
	PATHS 
		"src"
	NO_CMAKE_SYSTEM_PATH
)

IF( CIMG_INCLUDE_DIR)
	SET( CIMG_FOUND TRUE )
ENDIF( CIMG_INCLUDE_DIR)

IF( CIMG_FOUND )
		MESSAGE("ERGC> CIMG found: [${CIMG_INCLUDE_DIR}]")
ENDIF( CIMG_FOUND )


